-- Active: 1786667857908@@127.0.0.1@5432@bd_aula
CREATE TABLE curso(
    id_curso INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL
    id_curso INTEGER NOT NULL REFERENCES curso(id_curso)
);

CREATE TABLE aluno(
    id_aluno INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(60) NOT NULL,
    id_curso INTEGER NOT NULL REFERENCES curso(id_curso)
)